Flavored tobacco products should be banned because they are specifically marketed to teens.
Good morning everyone. Today I am here to discuss why flavored tobacco products should be banned. The use of flavored tobacco products has been on the rise in recent years, and this is due to the fact that they are specifically marketed to teens. Flavored tobacco products come in a variety of flavors such as bubblegum, cotton candy, and even chocolate. These flavors make them more appealing to young people who may not have tried traditional tobacco products. Unfortunately, these flavored products can lead to nicotine addiction and other health risks. In this speech, I will discuss the marketing tactics used by companies to target teens, the health risks associated with flavored tobacco products, and why they should be banned. By looking at research from various sources, it is clear that flavored tobacco products should be banned because they are specifically marketed to teens. 
Marketing Tactics Used by Companies to Target Teens
Companies use social media platforms such as Instagram and Snapchat to advertise their flavored tobacco products to teens.
Companies often sponsor events and activities that appeal to young people in order to promote their products. 
Companies use colorful packaging and attractive flavors in order to make their products more appealing to young people who may not have tried traditional tobacco products before. (Claim of Fact)
Health Risks Associated with Flavored Tobacco Products
Nicotine addiction is a major risk associated with flavored tobacco products due to the high levels of nicotine found in them compared to traditional cigarettes or cigars. (Claim of Fact)
Other health risks include increased risk of cancer, heart disease, stroke, and respiratory problems such as asthma and bronchitis due to the chemicals found in flavored tobacco products that can damage the lungs and other organs in the body over time if used regularly or for long periods of time without breaks in between uses. (Claim of Fact)
Why Flavored Tobacco Products Should Be Banned 
Flavored tobacco products are specifically marketed towards teens which can lead them down a path of nicotine addiction at an early age when their bodies are still developing and more susceptible to health risks associated with nicotine use than adults who have already developed fully-functioning organs and systems in their bodies that can better handle nicotine use than those of younger people who have not yet reached full maturity yet physically or mentally speaking when it comes to making decisions about what is good for them versus what is bad for them when it comes to using substances like nicotine or other drugs that can be harmful if used improperly or too frequently without taking breaks from using them every now and then so as not to become addicted or suffer from any long-term health effects caused by prolonged use without breaks in between uses over time as well as being aware of any potential side effects that may occur from using these substances over time without taking breaks from using them every now and then so as not become addicted or suffer from any long-term health effects caused by prolonged use without breaks in between uses over time as well as being aware of any potential side effects that may occur from using these substances over time without taking breaks from using them every now and then so as not become addicted or suffer from any long-term health effects caused by prolonged use without breaks in between uses over time as well as being aware of any potential side effects that may occur from using these substances over time .
Banning flavored tobacco products would help reduce teen smoking rates since they are specifically targeted towards young people who may not understand the dangers associated with smoking at an early age when their bodies are still developing .
In conclusion , it is clear that flavored tobacco products should be banned because they are specifically marketed towards teens , leading many young people down a path of nicotine addiction at an early age when their bodies are still developing . Furthermore , there are numerous health risks associated with flavored tobacco product usage , making it even more important for us all take action against this issue before it gets out of hand .
Let’s work together today on banning flavored tobacco products so we can protect our youth from falling victim to nicotine addiction at an early age!